name: ilmaris
favicon: null
layout_spectrum: 0.09830593131482601
typography_spectrum: 0.3521478164475411
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.15332396910525858
  lightness: 0.4621189469471574
  saturation: 0.929233588045463
  rhythmicContrast: 0.13926976453512907
purpose: []
